name: KeepAlive Classicube

on:
  workflow_dispatch:   # permite ejecutarlo manualmente

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar netcat
        run: |
          sudo apt-get update -y
          sudo apt-get install -y netcat-openbsd

      - name: Ping TCP y esperar 10 minutos
        run: |
          while true; do
              echo "$(date): Haciendo ping TCP a 51.81.59.76:20030"
              nc -z -v 51.81.59.76 20030 && echo "$(date): Conectado ✅" || echo "$(date): ERROR ❌"
              echo "Esperando 10 minutos..."
              sleep 600
          done
